name: ikos
base: core22
version: "3.2"
summary:  Static analyzer for C/C++ based on the theory of Abstract Interpretation
description: |
  IKOS (Inference Kernel for Open Static Analyzers) is a static analyzer for
  C/C++ based on the theory of Abstract Interpretation. It provides a C and C++
  static analyzer based on LLVM. It implements scalable analyses for detecting
  and proving the absence of runtime errors in C and C++ programs.

grade: stable
confinement: classic
license: NASA-1.3

apps:
  ikos:
    command: usr/bin/python3 $SNAP/usr/bin/ikos
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/site-packages
  analyzer:
    command: usr/bin/ikos-analyzer
  config:
    command: usr/bin/python3 $SNAP/usr/bin/ikos-config
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/site-packages
  import:
    command: usr/bin/ikos-import
  report:
    command: usr/bin/python3 $SNAP/usr/bin/ikos-report
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/site-packages
  scan:
    command: usr/bin/python3 $SNAP/usr/bin/ikos-scan
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/site-packages
  view:
    command: usr/bin/python3 $SNAP/usr/bin/ikos-view
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/site-packages

parts:
  ikos:
    plugin: cmake
    source: https://github.com/NASA-SW-VnV/ikos.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - clang
      - libclang-dev
      - llvm
      - llvm-dev
      - cmake
      - libgmp-dev
      - libboost-all-dev
      - python3
      - libsqlite3-dev
      - libtbb-dev
    stage-packages:
      - clang
      - libclang-dev
      - libgmp10
      - libsqlite3-0
      - libsqlite3-dev
      - libtbb12
      - libboost-filesystem1.74.0
      - libboost-thread1.74.0
      - libgmpxx4ldbl
      - libpython3.10-stdlib
      - llvm
      - llvm-dev
      - python3
      - python3-minimal
      - python3.10
      - python3.10-minimal
      - python3-pygments
    override-pull: |
      craftctl default
      # ensure the final code is snap aware
      sed -i "s|PREFIX = \(.*\)|PREFIX = os.getenv('SNAP', '/snap/ikos/current') + \1|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_CONFIG = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_PREFIX = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_BIN_DIR = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_INCLUDE_DIR = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_LIBRARY_DIR = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(CLANG = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(CLANGXX = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      # and fix a bug where the wrong flag is passed to llvm-objdump (since
      # llvm-10 this is now --section not -section)
      sed -i "s|cmd.append('-section=%s' % ELF_SECTION_NAME)|cmd.append('--section=%s' % ELF_SECTION_NAME)|" analyzer/python/ikos/scan.py
      # and which parses the output of llvm-objdump incorrectly (the output
      # format seems to have changed in more recent versions)
      sed -i "s|itertools.islice(output.splitlines(), 4, None)|itertools.islice(output.splitlines(), 3, None)|" analyzer/python/ikos/scan.py
    override-build: |
      craftctl default
      # fixup python interpreter path
      sed -i "s|$CRAFT_PART_INSTALL|/snap/ikos/current|" $CRAFT_PART_INSTALL/usr/bin/ikos*
