name: ikos
base: core22
version: "3.1"
summary:  Static analyzer for C/C++ based on the theory of Abstract Interpretation
description: |
  IKOS (Inference Kernel for Open Static Analyzers) is a static analyzer for
  C/C++ based on the theory of Abstract Interpretation. It provides a C and C++
  static analyzer based on LLVM. It implements scalable analyses for detecting
  and proving the absence of runtime errors in C and C++ programs.

grade: stable
confinement: classic

apps:
  ikos:
    command: usr/bin/ikos
  analyzer:
    command: usr/bin/ikos-analyzer
  config:
    command: usr/bin/ikos-config
  import:
    command: usr/bin/ikos-import
  report:
    command: usr/bin/ikos-report
  scan:
    command: usr/bin/ikos-scan
  view:
    command: usr/bin/ikos-view

parts:
  ikos:
    plugin: cmake
    source: https://github.com/NASA-SW-VnV/ikos.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - clang
      - libclang-dev
      - llvm
      - llvm-dev
      - cmake
      - libgmp-dev
      - libboost-all-dev
      - python3
      - libsqlite3-dev
      - libtbb-dev
      - python3-pygments
    stage-packages:
      - clang
      - libclang-dev
      - libgmp10
      - libsqlite3-0
      - libtbb12
      - libboost-filesystem1.74.0
      - libboost-thread1.74.0
      - libgmpxx4ldbl
      - llvm
      - llvm-dev
    override-pull: |
      craftctl default
      # ensure the final code is snap aware
      sed -i "s|PREFIX = \(.*\)|PREFIX = os.getenv('SNAP', '/snap/ikos/current') + \1|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_CONFIG = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_PREFIX = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_BIN_DIR = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_INCLUDE_DIR = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(LLVM_LIBRARY_DIR = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(CLANG = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
      sed -i "s|\(CLANGXX = .*\)|\1.replace('"$SNAPCRAFT_PART_INSTALL"', os.getenv('SNAP', '/snap/ikos/current'))|" analyzer/python/ikos/settings.py.in
    override-build: |
      craftctl default
      # snapcraft won't allow an application with c++ in the binary name so
      # symlink one as cpp
      ln -s ikos-scan-c++ $CRAFT_PART_INSTALL/usr/bin/ikos-scan-cpp
